version: '3.3'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - '4000:4000'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - PORT=4000
  test:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'test']
